CREATE DATABASE IF NOT EXISTS PROYECTO_2;
USE PROYECTO_2;

CREATE TABLE IF NOT EXISTS DEPARTAMENTO (
	codigo INTEGER PRIMARY KEY,
    nombre VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS MUNICIPIO (
	codigo INTEGER,
    nombre VARCHAR(30) NOT NULL,
    departamento INTEGER,
    FOREIGN KEY (departamento) REFERENCES DEPARTAMENTO(codigo),
    PRIMARY KEY (codigo, departamento)
);

CREATE TABLE IF NOT EXISTS PERSONA (
	cui INTEGER PRIMARY KEY,
    nombre_1 VARCHAR(20) NOT NULL,
    nombre_2 VARCHAR(20),
    nombre_3 VARCHAR(20),
    apellido_1 VARCHAR(25) NOT NULL,
    apellido_2 VARCHAR(25),
    genero CHAR(1) NOT NULL,
    CONSTRAINT CHECKGENDER CHECK (genero in ('M','F'))
);

CREATE TABLE IF NOT EXISTS DEFUNCION (
	no_acta INTEGER PRIMARY KEY AUTO_INCREMENT,
    fecha DATE NOT NULL,
    cui INTEGER NOT NULL UNIQUE,
    FOREIGN KEY (cui) REFERENCES PERSONA(cui) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS LICENCIA (
	numero INTEGER PRIMARY KEY AUTO_INCREMENT,
    fecha DATE NOT NULL,
    tipo CHAR(1) NOT NULL,
    cui INTEGER NOT NULL,
    FOREIGN KEY (cui) REFERENCES PERSONA(cui) ON DELETE CASCADE,
    CONSTRAINT TYPECHECK CHECK (tipo IN ('A','B','C','M','E'))
);

CREATE TABLE IF NOT EXISTS ANULACION (
	numero INTEGER PRIMARY KEY AUTO_INCREMENT,
    fecha DATE NOT NULL,
    licencia INTEGER NOT NULL,
    FOREIGN KEY (licencia) REFERENCES LICENCIA(numero) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS NACIMIENTO (
	no_acta INTEGER PRIMARY KEY AUTO_INCREMENT,
    fecha DATE NOT NULL,
    cui INTEGER NOT NULL,
    cui_madre INTEGER NOT NULL,
    cui_padre INTEGER NOT NULL,
    municipio INTEGER NOT NULL,
    departamento INTEGER NOT NULL,
    FOREIGN KEY (cui) REFERENCES PERSONA(cui) ON DELETE CASCADE,
    FOREIGN KEY (cui_padre) REFERENCES PERSONA(cui) ON DELETE CASCADE,
    FOREIGN KEY (cui_madre) REFERENCES PERSONA(cui) ON DELETE CASCADE,
    FOREIGN KEY (municipio) REFERENCES MUNICIPIO(codigo) ON DELETE CASCADE,
    FOREIGN KEY (departamento) REFERENCES MUNICIPIO(departamento) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DPI (
	fecha DATE NOT NULL,
    municipio INTEGER NOT NULL,
    departamento INTEGER NOT NULL,
    cui INTEGER,
    FOREIGN KEY (municipio) REFERENCES MUNICIPIO(codigo) ON DELETE CASCADE,
    FOREIGN KEY (departamento) REFERENCES MUNICIPIO(departamento) ON DELETE CASCADE,
    FOREIGN KEY (cui) REFERENCES PERSONA(cui) ON DELETE CASCADE,
    PRIMARY KEY (cui)
);

CREATE TABLE IF NOT EXISTS MATRIMONIO (
	no_acta INTEGER PRIMARY KEY AUTO_INCREMENT,
    fecha DATE NOT NULL,
    cui_novio INTEGER NOT NULL,
    cui_novia INTEGER NOT NULL,
    FOREIGN KEY (cui_novio) REFERENCES PERSONA(cui) ON DELETE CASCADE,
    FOREIGN KEY (cui_novia) REFERENCES PERSONA(cui) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DIVORCIO (
	no_acta INTEGER PRIMARY KEY AUTO_INCREMENT,
    fecha DATE NOT NULL,
    matrimonio INTEGER NOT NULL,
    FOREIGN KEY (matrimonio) REFERENCES MATRIMONIO(no_acta) ON DELETE CASCADE
);